ERROR - 2023-12-05 05:07:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp\htdocs\dishtavo2\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 G:\xampp\htdocs\dishtavo2\system\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', Array, NULL, 'username')
#6 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', Array, Array)
#7 G:\xampp\htdocs\dishtavo2\app\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
#8 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
#9 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
#10 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp\htdocs\dishtavo2\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp\htdocs\dishtavo2\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 G:\xampp\htdocs\dishtavo2\system\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#4 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', Array, NULL, 'username')
#5 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', Array, Array)
#6 G:\xampp\htdocs\dishtavo2\app\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
#7 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
#8 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
#9 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\dishtavo2\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-05 05:07:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', [...], [...])
 6 APPPATH\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-05 05:15:34 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'ci4' in G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp\htdocs\dishtavo2\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 G:\xampp\htdocs\dishtavo2\system\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', Array, NULL, 'username')
#6 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', Array, Array)
#7 G:\xampp\htdocs\dishtavo2\app\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
#8 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
#9 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
#10 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp\htdocs\dishtavo2\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'ci4' in G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp\htdocs\dishtavo2\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 G:\xampp\htdocs\dishtavo2\system\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#4 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', Array, NULL, 'username')
#5 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', Array, Array)
#6 G:\xampp\htdocs\dishtavo2\app\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
#7 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
#8 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
#9 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\dishtavo2\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-05 05:15:34 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'ci4'
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', [...], [...])
 6 APPPATH\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-05 05:22:03 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'ci4' in G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp\htdocs\dishtavo2\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 G:\xampp\htdocs\dishtavo2\system\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', Array, NULL, 'username')
#6 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', Array, Array)
#7 G:\xampp\htdocs\dishtavo2\app\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
#8 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
#9 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
#10 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp\htdocs\dishtavo2\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'ci4' in G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp\htdocs\dishtavo2\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 G:\xampp\htdocs\dishtavo2\system\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#4 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', Array, NULL, 'username')
#5 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', Array, Array)
#6 G:\xampp\htdocs\dishtavo2\app\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
#7 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
#8 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
#9 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp\htdocs\dishtavo2\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-12-05 05:22:03 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'ci4'
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', [...], [...])
 6 APPPATH\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-05 05:22:26 --> mysqli_sql_exception: Table 'dishtavo.users' doesn't exist in G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 G:\xampp\htdocs\dishtavo2\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT 1\nFROM `...', 0)
#1 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 G:\xampp\htdocs\dishtavo2\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 G:\xampp\htdocs\dishtavo2\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 G:\xampp\htdocs\dishtavo2\system\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', Array, NULL, 'username')
#6 G:\xampp\htdocs\dishtavo2\system\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', Array, Array)
#7 G:\xampp\htdocs\dishtavo2\app\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
#8 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
#9 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
#10 G:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp\htdocs\dishtavo2\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-12-05 05:22:26 --> Table 'dishtavo.users' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Validation\StrictRules\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\Validation\Validation.php(311): CodeIgniter\Validation\StrictRules\Rules->is_unique('bhakti', 'username', [...], null, 'username')
 4 SYSTEMPATH\Validation\Validation.php(197): CodeIgniter\Validation\Validation->processRules('username', 'username', 'bhakti', [...], [...])
 5 APPPATH\Controllers\admin\Login.php(45): CodeIgniter\Validation\Validation->run()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\admin\Login->validatelogin()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\Login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-05 06:32:35 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 252.
 1 SYSTEMPATH\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-12-05 06:32:37 --> Uncaught Error: Class 'Locale' not found in D:\xampp\htdocs\dishtavo2\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\xampp\htdocs\dishtavo2\system\Helpers\number_helper.php(55): format_number(6, 2, NULL, Array)
#1 D:\xampp\htdocs\dishtavo2\system\Debug\BaseExceptionHandler.php(145): number_to_size(6, 2)
#2 D:\xampp\htdocs\dishtavo2\app\Views\errors\html\error_exception.php(361): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(6291456)
#3 D:\xampp\htdocs\dishtavo2\system\Debug\BaseExceptionHandler.php(241): include('D:\\xampp\\htdocs...')
#4 D:\xampp\htdocs\dishtavo2\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\xampp\htdocs\dishtavo2\system\Debug\ExceptionHandler.php(112): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\xampp\\htdocs...')
#6 D:\xampp\htdocs\dishtavo2\system\Debug\Exceptions.php(149): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\dishtavo2\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-12-05 06:34:40 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 252.
 1 SYSTEMPATH\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-12-05 06:34:40 --> Uncaught Error: Class 'Locale' not found in D:\xampp\htdocs\dishtavo2\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\xampp\htdocs\dishtavo2\system\Helpers\number_helper.php(55): format_number(6, 2, NULL, Array)
#1 D:\xampp\htdocs\dishtavo2\system\Debug\BaseExceptionHandler.php(145): number_to_size(6, 2)
#2 D:\xampp\htdocs\dishtavo2\app\Views\errors\html\error_exception.php(361): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(6291456)
#3 D:\xampp\htdocs\dishtavo2\system\Debug\BaseExceptionHandler.php(241): include('D:\\xampp\\htdocs...')
#4 D:\xampp\htdocs\dishtavo2\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\xampp\htdocs\dishtavo2\system\Debug\ExceptionHandler.php(112): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\xampp\\htdocs...')
#6 D:\xampp\htdocs\dishtavo2\system\Debug\Exceptions.php(149): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\dishtavo2\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-12-05 06:35:18 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 252.
 1 SYSTEMPATH\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-12-05 06:35:18 --> Uncaught Error: Class 'Locale' not found in D:\xampp\htdocs\dishtavo2\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\xampp\htdocs\dishtavo2\system\Helpers\number_helper.php(55): format_number(6, 2, NULL, Array)
#1 D:\xampp\htdocs\dishtavo2\system\Debug\BaseExceptionHandler.php(145): number_to_size(6, 2)
#2 D:\xampp\htdocs\dishtavo2\app\Views\errors\html\error_exception.php(361): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(6291456)
#3 D:\xampp\htdocs\dishtavo2\system\Debug\BaseExceptionHandler.php(241): include('D:\\xampp\\htdocs...')
#4 D:\xampp\htdocs\dishtavo2\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\xampp\htdocs\dishtavo2\system\Debug\ExceptionHandler.php(112): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\xampp\\htdocs...')
#6 D:\xampp\htdocs\dishtavo2\system\Debug\Exceptions.php(149): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\xampp\htdocs\dishtavo2\system\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\dishtavo2\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
